### ISSUE TITLE
Empty folder ".AndroidStudio2.1" in user Profile

### ISSUE THREAD

**Issue by NdYGA** [toksaitov/AndroidStudioPortable#1]
In the system folder for Your user profile is created an empty folder. AndroidStudio 2.1.
My proposed solution:
to add the string
**-Duser.home=${idea.home}/../../portable-home/**
in 
studio64.exe.vmoptions
my work env is Windows 10

**Comment by toksaitov** [comment]
@NdYGA
Thank you for your suggestion. It seems to be working fine on Windows 7 too.

**Comment by NdYGA** [comment]
You're welcome. Taking this opportunity, my gratitude for the diamond project.
