### ISSUE TITLE
No longer works due to Java JDK

### ISSUE THREAD

**Issue by ArmorDarks** [toksaitov/AndroidStudioPortable#4]
Hi!

It seems that old Java JDK no longer available for download.

I've changed URL to point to newer, version 9 JDK, but it turned out its internal structure has been significantly altered. I've tried to adapt the code to changes, but it seems that... well, mostly didn't turn out to work well.

Any plans to update to newer JDK version?

**Comment by hhocker** [comment]
From what I can see there is no requirement for JDK 9 or 10 (and some folks think that it might not work. https://stackoverflow.com/a/50240252) so sticking with JDK 8 makes sense. We probably just need to get the download link for the JDK updated to the latest JDK8uXXX. Simply edit the definitions file to point to the latest file.
